fix pipeline

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -94,32 +94,16 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           path: artifacts
+      - name: list artifacts
+        shell: bash
+        run: |
+          echo "Listing all artifacts in the 'artifacts' directory:"
+          ls -R artifacts
+          exit 1 # Fail the job to see the output in the logs
       - uses: nowsprinting/check-version-format-action@v3
         id: version
         with:
           prefix: 'v'
-      - name: Copy DLLs to NuGet structure
-        shell: bash
-        run: |
-          mkdir -p LoroCs/runtimes/win-x64/native
-          mkdir -p LoroCs/runtimes/win-x86/native
-          mkdir -p LoroCs/runtimes/win-arm64/native
-          mkdir -p LoroCs/runtimes/linux-x64/native
-          mkdir -p LoroCs/runtimes/linux-x86/native
-          mkdir -p LoroCs/runtimes/linux-arm64/native
-          mkdir -p LoroCs/runtimes/osx-x64/native
-          mkdir -p LoroCs/runtimes/osx-arm64/native
-
-          cp artifacts/loro-cs-x86_64-pc-windows-msvc/loro_cs.dll LoroCs/runtimes/win-x64/native/ || true
-          cp artifacts/loro-cs-i686-pc-windows-msvc/loro_cs.dll LoroCs/runtimes/win-x86/native/ || true
-          cp artifacts/loro-cs-aarch64-pc-windows-msvc/loro_cs.dll LoroCs/runtimes/win-arm64/native/ || true
-
-          cp artifacts/loro-cs-x86_64-unknown-linux-gnu/loro_cs.so LoroCs/runtimes/linux-x64/native/ || true
-          cp artifacts/loro-cs-i686-unknown-linux-gnu/loro_cs.so LoroCs/runtimes/linux-x86/native/ || true
-          cp artifacts/loro-cs-aarch64-unknown-linux-gnu/loro_cs.so LoroCs/runtimes/linux-arm64/native/ || true
-
-          cp artifacts/loro-cs-x86_64-apple-darwin/loro_cs.dylib LoroCs/runtimes/osx-x64/native/ || true
-          cp artifacts/loro-cs-aarch64-apple-darwin/loro_cs.dylib LoroCs/runtimes/osx-arm64/native/ || true
       - name: build
         run: |
           dotnet publish LoroCs/LoroCs/LoroCs.csproj -c Release -p:Version=${{ steps.version.outputs.full_without_prefix }}
